AWSTemplateFormatVersion: '2010-09-09'
Description: AWS::DynamoDB::Table - api-db - resources

Parameters:
  Build:
    Type: String

  ItemTableName:
    Type: String

  EventTableName:
    Type: String

Resources:

  # So we avoid ValidationError("No updates are to be performed") by changing the build number
  DummyResource:
    Metadata:
      Build:
        Ref: Build
    Type: AWS::CloudFormation::WaitConditionHandle

  ItemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: prn
          AttributeType: S
        - AttributeName: parent_prn
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: prn
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: parent-created_at-index
          KeySchema:
            - AttributeName: parent_prn
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TableName:
        Ref: ItemTableName

  EventTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: prn
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: prn
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      TableName:
        Ref: EventTableName

Outputs:

  ItemTableArn:
    Value:
      Fn::GetAtt: [ItemTable, Arn]

  EventTableArn:
    Value:
      Fn::GetAtt: [EventTable, Arn]
